// constants/errorCodes.js

const ERROR_CODES = {
  // User-related error codes
  USER: {
    CREATE_FAILED: "USER_CREATE_FAILED",
    NOT_FOUND: "USER_NOT_FOUND",
    UPDATE_FAILED: "USER_UPDATE_FAILED",
    DELETE_FAILED: "USER_DELETE_FAILED",
    DUPLICATE_EMAIL: "USER_DUPLICATE_EMAIL",
  },

  // Authentication and Authorization error codes
  AUTH: {
    LOGIN_FAILED: "AUTH_LOGIN_FAILED",
    UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    FORBIDDEN: "AUTH_FORBIDDEN",
    TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    PASSWORD_INVALID: "AUTH_PASSWORD_INVALID",
    PASSWORD_MISMATCH: "AUTH_PASSWORD_MISMATCH",
    URL_NOT_FOUND: "AUTH_URL_NOT_FOUND",
  },

  SCHOOL: {
    NOT_FOUND: "SCHOOL_NOT_FOUND",
    CREATE_FAILED: "SCHOOL_CREATE_FAILED",
    UPDATE_FAILED: "SCHOOL_UPDATE_FAILED",
    DELETE_FAILED: "SCHOOL_DELETE_FAILED",
    DUPLICATE_NAME: "SCHOOL_DUPLICATE_NAME",
  },
};

export default ERROR_CODES;
