// constants/errorCodes.js

const ERROR_CODES = {
    // User-related error codes
    USER: {
      CREATE_FAILED: "USER_CREATE_FAILED",
      NOT_FOUND: "USER_NOT_FOUND",
      UPDATE_FAILED: "USER_UPDATE_FAILED",
      DELETE_FAILED: "USER_DELETE_FAILED",
      DUPLICATE_EMAIL: "USER_DUPLICATE_EMAIL",
    },
  
    // Authentication and Authorization error codes
    AUTH: {
      LOGIN_FAILED: "AUTH_LOGIN_FAILED",
      UNAUTHORIZED: "AUTH_UNAUTHORIZED",
      FORBIDDEN: "AUTH_FORBIDDEN",
      TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
      TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    },
  
    // Validation error codes
    VALIDATION: {
      REQUIRED_FIELD: "VALIDATION_REQUIRED_FIELD",
      INVALID_EMAIL: "VALIDATION_INVALID_EMAIL",
      PASSWORD_TOO_SHORT: "VALIDATION_PASSWORD_TOO_SHORT",
      PASSWORD_TOO_WEAK: "VALIDATION_PASSWORD_TOO_WEAK",
      INVALID_REQUEST: "VALIDATION_INVALID_REQUEST",
      INVALID_FORMAT: "VALIDATION_INVALID_FORMAT",
    },
  
    // General error codes
    GENERAL: {
      SERVER_ERROR: "GENERAL_SERVER_ERROR",
      BAD_REQUEST: "GENERAL_BAD_REQUEST",
      NOT_FOUND: "GENERAL_NOT_FOUND",
      UNPROCESSABLE_ENTITY: "GENERAL_UNPROCESSABLE_ENTITY",
      OPERATION_FAILED: "GENERAL_OPERATION_FAILED",
      CONFLICT: "GENERAL_CONFLICT",
    },
  
    // Database error codes
    DATABASE: {
      CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
      QUERY_FAILED: "DATABASE_QUERY_FAILED",
      TIMEOUT: "DATABASE_TIMEOUT",
      CONSTRAINT_VIOLATION: "DATABASE_CONSTRAINT_VIOLATION",
    },
  
    // External service error codes
    EXTERNAL: {
      EMAIL_SEND_FAILED: "EXTERNAL_EMAIL_SEND_FAILED",
      SERVICE_UNAVAILABLE: "EXTERNAL_SERVICE_UNAVAILABLE",
      TIMEOUT: "EXTERNAL_TIMEOUT",
      RATE_LIMIT_EXCEEDED: "EXTERNAL_RATE_LIMIT_EXCEEDED",
    },
  
    // Logging error codes
    LOG: {
      CREATE_FAILED: "LOG_CREATE_FAILED",
      UPDATE_FAILED: "LOG_UPDATE_FAILED",
      DELETE_FAILED: "LOG_DELETE_FAILED",
    },
  };
  
  export default ERROR_CODES;
  